import { app, nativeImage } from 'electron'
import { join, basename, extname, dirname } from 'path'
import { existsSync } from 'fs'
import { readdir, readFile, writeFile, rm } from 'fs/promises'

// A live filesystem browser: the renderer navigates the user's own folders and
// nothing is copied. Reads happen here (main process) via fs; the renderer only
// receives directory listings, on-demand thumbnails, and (on drag) file bytes.

export interface DirEntry {
  name: string
  path: string
  isDirectory: boolean
  type: string // mime, empty for directories
}

export interface Shortcut {
  label: string
  path: string
}

export interface BrowserState {
  pinned: string[]
  lastDir: string | null
}

const MIME: Record<string, string> = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.bmp': 'image/bmp',
  '.svg': 'image/svg+xml',
  '.pdf': 'application/pdf',
  '.txt': 'text/plain',
  '.md': 'text/markdown',
  '.json': 'application/json',
  '.csv': 'text/csv',
  '.mp3': 'audio/mpeg',
  '.wav': 'audio/wav',
  '.flac': 'audio/flac',
  '.m4a': 'audio/mp4',
  '.aac': 'audio/aac',
  '.ogg': 'audio/ogg',
  '.mp4': 'video/mp4',
  '.mov': 'video/quicktime',
  '.mkv': 'video/x-matroska',
  '.webm': 'video/webm',
  '.zip': 'application/zip'
}

function mimeFor(name: string): string {
  return MIME[extname(name).toLowerCase()] ?? 'application/octet-stream'
}

/** Common OS locations that actually exist. */
export function shortcuts(): Shortcut[] {
  const defs: [string, 'home' | 'desktop' | 'documents' | 'downloads'][] = [
    ['Home', 'home'],
    ['Bureaublad', 'desktop'],
    ['Documenten', 'documents'],
    ['Downloads', 'downloads']
  ]
  const out: Shortcut[] = []
  for (const [label, key] of defs) {
    try {
      const p = app.getPath(key)
      if (existsSync(p)) out.push({ label, path: p })
    } catch {
      /* not available on this OS */
    }
  }
  return out
}

/**
 * List a directory. Uses withFileTypes so no per-entry stat is needed — stays
 * fast even for large folders. Hidden dotfiles are skipped. Directories first,
 * then files, alphabetically.
 */
export async function listDir(dirPath: string): Promise<{ path: string; entries: DirEntry[] }> {
  const dirents = await readdir(dirPath, { withFileTypes: true })
  const entries: DirEntry[] = []
  for (const d of dirents) {
    if (d.name.startsWith('.')) continue
    const isDirectory = d.isDirectory()
    entries.push({
      name: d.name,
      path: join(dirPath, d.name),
      isDirectory,
      type: isDirectory ? '' : mimeFor(d.name)
    })
  }
  entries.sort(
    (a, b) =>
      Number(b.isDirectory) - Number(a.isDirectory) ||
      a.name.localeCompare(b.name, 'nl', { sensitivity: 'base' })
  )
  return { path: dirPath, entries }
}

/** A small PNG thumbnail for an image file, generated by the OS. Null on failure. */
export async function thumbnail(filePath: string): Promise<Buffer | null> {
  try {
    const img = await nativeImage.createThumbnailFromPath(filePath, { width: 64, height: 64 })
    if (img.isEmpty()) return null
    return img.toPNG()
  } catch {
    return null
  }
}

/** Raw bytes of a file — read on demand when a file is dragged onto a tool. */
export async function readFileBytes(
  filePath: string
): Promise<{ name: string; type: string; data: Buffer }> {
  const data = await readFile(filePath)
  return { name: basename(filePath), type: mimeFor(filePath), data }
}

// ---- Persisted state: pinned locations + last-viewed dir (paths only) -------
function stateFile(): string {
  return join(app.getPath('userData'), 'browser-state.json')
}

export async function getState(): Promise<BrowserState> {
  try {
    const d = JSON.parse(await readFile(stateFile(), 'utf-8'))
    return {
      pinned: Array.isArray(d?.pinned) ? d.pinned.filter((p: unknown) => typeof p === 'string') : [],
      lastDir: typeof d?.lastDir === 'string' ? d.lastDir : null
    }
  } catch {
    return { pinned: [], lastDir: null }
  }
}

async function saveState(s: BrowserState): Promise<void> {
  await writeFile(stateFile(), JSON.stringify(s, null, 2), 'utf-8')
}

export async function pinDir(path: string): Promise<string[]> {
  const s = await getState()
  if (!s.pinned.includes(path)) s.pinned.push(path)
  await saveState(s)
  return s.pinned
}

export async function unpinDir(path: string): Promise<string[]> {
  const s = await getState()
  s.pinned = s.pinned.filter((p) => p !== path)
  await saveState(s)
  return s.pinned
}

export async function setLastDir(path: string): Promise<void> {
  const s = await getState()
  s.lastDir = path
  await saveState(s)
}

export function isDir(path: string): boolean {
  return existsSync(path)
}

export function parentOf(path: string): string {
  return dirname(path)
}

/** One-time removal of the old copy-based collection (replaced by this browser). */
export async function cleanupLegacyCollectedFiles(): Promise<void> {
  const base = app.getPath('userData')
  try {
    await rm(join(base, 'collected-files'), { recursive: true, force: true })
  } catch {
    /* nothing to clean */
  }
  try {
    await rm(join(base, 'collected-files.json'), { force: true })
  } catch {
    /* nothing to clean */
  }
}
